<?php

/*
 * sync*gw RoundCube Bundle
 *
 * @copyright  https://syncgw.com, 2017 - 2021
 * @author     Florian Daeumling, https://syncgw.com
 * @license    http://opensource.org/licenses/lgpl-3.0.html
 */

$labels['syncgw_p_title']   = 'Synchronisationseinstellungen';
$labels['syncgw_m_head']    = 'Mailbox mit sync&bull;gw synchronisieren';
$labels['syncgw_m_text']    = 'Alle Ordner';
$labels['syncgw_a_head']    = 'Adressbücher mit sync&bull;gw synchronisieren';
$labels['syncgw_a_tonly']   = 'Nur Kontakte mit Telefonnummern';
$labels['syncgw_c_head']    = 'Kalender mit sync&bull;gw synchronisieren';
$labels['syncgw_t_head']    = 'Aufgabenlisten mit sync&bull;gw synchronisieren';
$labels['syncgw_n_head']    = 'Notizen mit sync&bull;gw synchronisieren';
$labels['syncgw_n_text']    = 'Persönliche Notizen';

?>