<?php

/*
 * sync*gw RoundCube Bundle
 *
 * @copyright  http://syncgw.com, 2017 - 2018
 * @author     Florian Daeumling, http://syncgw.com
 * @license    http://opensource.org/licenses/lgpl-3.0.html
 */

$labels['syncgw_p_title']   = 'Synchronization Settings';
$labels['syncgw_a_head']    = 'Synchronize address book with sync&bull;gw';
$labels['syncgw_a_tonly']   = 'Only contacts with phone numbers';
$labels['syncgw_c_head']    = 'Synchronize calendar with sync&bull;gw';
$labels['syncgw_t_head']    = 'Synchronize task list with sync&bull;gw';

?>