<?php

/*
 * sync*gw RoundCube Bundle
 *
 * @copyright  http://syncgw.com, 2017 - 2020
 * @author     Florian Daeumling, http://syncgw.com
 * @license    http://opensource.org/licenses/lgpl-3.0.html
 */

$labels['syncgw_p_title']   = 'Synchronization settings';
$labels['syncgw_m_head']    = 'Synchronize mail box with sync&bull;gw';
$labels['syncgw_m_text']    = 'All folder';
$labels['syncgw_a_head']    = 'Synchronize address book with sync&bull;gw';
$labels['syncgw_a_tonly']   = 'Only contacts with phone numbers';
$labels['syncgw_c_head']    = 'Synchronize calendar with sync&bull;gw';
$labels['syncgw_t_head']    = 'Synchronize task list with sync&bull;gw';
$labels['syncgw_n_head']    = 'Synchronize notes with sync&bull;gw';
$labels['syncgw_n_text']    = 'Personal notes';

?>