<?php

/*
 * sync*gw RoundCube Bundle
 *
 * @copyright  http://syncgw.com, 2017 - 2018
 * @author     Florian Daeumling, http://syncgw.com
 * @license    http://opensource.org/licenses/lgpl-3.0.html
 */

$labels = [
    $labels['syncgw_p_title']   = 'Synchronisationseinstellungen',
    $labels['syncgw_a_head']    = 'Adressbücher mit sync&bull;gw synchronisieren',
    $labels['syncgw_a_tonly']   = 'Nur Kontakte mit Telefonnummern',
    $labels['syncgw_c_head']    = 'Kalender mit sync&bull;gw synchronisieren',
    $labels['syncgw_t_head']    = 'Aufgabenlisten mit sync&bull;gw synchronisieren',
];

?>